### ISSUE TITLE
users manage.py commands broken

### ISSUE THREAD

**Issue by Amdingo** [testdrivenio/testdriven-app-2.3#21]
I'm sure its some package that I haven't tracked yet - though it could be something with docker itself - but if you build the project currently the flask cli commands aren't recognized.  Below is from cloning and building the repository about 5 minutes before posting this issue.

```
$ docker-compose -f docker-compose-dev.yml run users python manage.py recreate_db
Starting testdriven-app-23_users-db_1 ... done
Usage: manage.py [OPTIONS] COMMAND [ARGS]...
Try "manage.py --help" for help.

Error: No such command "recreate_db".
```

**Comment by mjhea0** [comment]
Hi @Amdingo,

Yes, this is due to a recent breaking change with the Click library -> https://github.com/pallets/click/issues/1123.

Change the command from `recreate_db` to `recreate-db`:

```
docker-compose -f docker-compose-dev.yml run users python manage.py recreate-db
```

I am going through and updating blog posts and should have a new release of the course out next week that fixes this.

Thanks!

**Comment by mjhea0** [comment]
Fixed. New release went out last week.

**Comment by eadomenech** [comment]
The same with seed_db:
`docker-compose -f docker-compose-dev.yml run users python manage.py seed-db`
